### ISSUE TITLE
 Pull request syntax to vim/vim 

### ISSUE THREAD

**Issue by 89z** [google/vim-ft-go#10]
Currently Vim is using another syntax for Go:

https://github.com/vim/vim/blob/master/runtime/syntax/go.vim

I like the  `google/vim-ft-go` better, as the colors seem to be improved (for example `nil` color). Can you open an issue or pull request at the `vim/vim`? I would do it myself, but they prefer maintainer to do it.

**Comment by dbarnett** [comment]
Interesting, didn't they pull the one currently in vim from https://github.com/fatih/vim-go? Happy to help improve things, but if they're accepting PRs to get the best of both, that might be simpler.

Did you close this because you changed your mind, or something else?

**Comment by 89z** [comment]
> Interesting, didn't they pull the one currently in vim from https://github.com/fatih/vim-go? Happy to help improve things, but if they're accepting PRs to get the best of both, that might be simpler.
> 
> Did you close this because you changed your mind, or something else?

I screwed up.

Six months ago, `google/vim-ft-go` was being used at `vim/vim`. I didnt know it at the time, but in hindsight that was probably the best package to be using. But, the package did have problems [1]. So in addition to working to fix those issues, I also had the idea of switching Go packages, in case I didnt have luck getting the changes made upstream (here). Well, the changes did get made here, but since I set the ball rolling on changing the Go package, it ended up happening two months ago [2].

I revisted the whole situation today, and I found yet another issue here [3], so I thought about just using the other package, which comes with Vim now. However I wasnt happy, because they are doing weird stuff with the color. So I decided to try the upstream `fatih/vim-go`, but I found out that it doesnt work without plugins. I just want a simple syntax file that I can drop in.

So at this point I dont know what to do. I guess I will keep keep using `google/vim-ft-go`, I just wish I left well enough alone I guess.

1. https://github.com/google/vim-ft-go/issues/6
2. https://github.com/vim/vim/commit/90df4b9d
3. https://github.com/google/vim-ft-go/issues/11

**Comment by dbarnett** [comment]
Yeah, one way or another I'd love to have a good go syntax file built into vim. I set up this repo just as a staging area for upstreaming changes, but moving to fatih's repo and obsoleting this one simplifies some things. Definitely worth getting issues filed to track the shortcomings there, though.
