### ISSUE TITLE
Underscore in number literals

### ISSUE THREAD

**Issue by 89z** [google/vim-ft-go#6]
Go numbers allow for underscores:

~~~go
package main

func main() {
   n := 1_000
   println(n)
}
~~~

- https://golang.org/ref/spec#Floating-point_literals
- https://golang.org/ref/spec#Integer_literals

however in the above program, the `1_000` is not recognized as a number. I think
the issue is here:

https://github.com/google/vim-ft-go/blob/e9b820bc30467fa151f1ebd63222648ec71e022f/syntax/go.vim#L137-L139
https://github.com/google/vim-ft-go/blob/e9b820bc30467fa151f1ebd63222648ec71e022f/syntax/go.vim#L148-L151

**Comment by 89z** [comment]
Side note, `E` and `e` are never part of integers, so that could be removed as well

**Comment by dbarnett** [comment]
Thanks for catching that! Adding the underscores isn't too hard, but I'll need a chance to check corner cases before I can submit any fixes.

I also noticed a few other obvious issues like not handling explicit bin/octal prefixes `0b`/`0o`, and several of the other sample int/float literals from that doc not highlighted correctly for whatever reason.

**Comment by 89z** [comment]
https://github.com/google/vim-ft-go/pull/7
